# example netlify.toml
[build]
  command = "npm run build"
  functions = "netlify/functions"
  publish = "build"

  [[redirects]]
    from = "/api/*"
    to = "https://api.mangadex.org/:splat"
    status = 200
    force = true

  [[redirects]]
    from = "/image/*"
    to = "https://mangadb-search.herokuapp.com/image/:splat"
    status = 200
    force = true

  [[redirects]]
    from = "/mdh/*"
    to = "https://mangadb-search.herokuapp.com/mdh/:splat"
    status = 200
    force = true

  [[redirects]]
    from = "/mangadb/*"
    to = "https://mangadb-search.herokuapp.com/mangadb/:splat"
    status = 200
    force = true

  # Uncomment to use this redirect for Single Page Applications like create-react-app.
  # Not needed for static site generators.
  [[redirects]]
    from = "/*"
    to = "/index.html"
    status = 200

  ## (optional) Settings for Netlify Dev
  ## https://github.com/netlify/cli/blob/master/docs/netlify-dev.md#project-detection
  #[dev]
  #  command = "yarn start" # Command to start your dev server
  #  port = 3000 # Port that the dev server will be listening on
  #  publish = "dist" # Folder with the static content for _redirect file

  ## more info on configuring this file: https://www.netlify.com/docs/netlify-toml-reference/
